# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
env:
  - NOT_CRAN=true
r_packages:
  - covr
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmagick++-dev
after_success:
  - Rscript -e 'library(covr); codecov(quiet = FALSE)'
