# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
sudo: false
cache: packages
env:
  - NOT_CRAN=true
  - NOT_CRAN=false
r_packages:
  - covr
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmagick++-dev
after_success:
  - if [ "$NOT_CRAN" = "true" -a "$TRAVIS_R_VERSION_STRING" = "release" ]; then Rscript -e 'library(covr); codecov(quiet = FALSE)'; fi